kind: Template
apiVersion: v1
metadata:
  name: zookeeper-1-node
  creationTimestamp:
  annotations:
    openshift.io/display-name: Zookeeper
    description: An example of a replicated Zookeeper server
    iconClass: icon-database
    tags: database,zookeeper
labels:
  template: zookeeper
parameters:
- name: ZOOKEEPER_IMAGE
  displayName: ZOOKEEPER_IMAGE
  description: The name of Zookeeper Docker image to use
  required: true
  value: bbvalabs/zookeeper
- name: VOLUME_CAPACITY
  displayName: VOLUME_CAPACITY
  description: Persistent volume capacity per pod, e.g. 512Mi, 2Gi
  required: true
  value: 512Mi
- name: ZOO_USER
  displayName: ZOO_USER
  description: Zookeeper user
  required: true
  value: zookeeper
- name: ZOO_CONF_DIR
  displayName: ZOO_CONF_DIR
  description: Path for configuration directory
  required: true
  value: /conf
- name: ZOO_DATA_DIR
  displayName: ZOO_DATA_DIR
  description: Path for data directory
  required: true
  value: /data
- name: ZOO_DATA_LOG_DIR
  displayName: ZOO_DATA_LOG_DIR
  description: Path for log directory
  required: true
  value: /datalog
- name: ZOO_TICK_TIME
  displayName: ZOO_TICK_TIME
  description: The number of milliseconds of each tick
  required: true
  value: '2000'
- name: ZOO_INIT_LIMIT
  displayName: ZOO_INIT_LIMIT
  description: The number of ticks that the initial synchronization phase can take
  required: true
  value: '5'
- name: ZOO_SYNC_LIMIT
  displayName: ZOO_SYNC_LIMIT
  description: The number of ticks that can pass between sending a request and getting an acknowledgement
  required: true
  value: '2'
- name: ZOO_PORT
  displayName: ZOO_PORT
  description: The port at which the clients will connect
  required: true
  value: '2181'
- name: ZOO_MAX_CLIENT_CNXNS
  displayName: ZOO_MAX_CLIENT_CNXNS
  description: The maximum number of client connections
  required: true
  value: '60'
- name: ZOO_AUTOPURGE_SANPRETAINCOUNT
  displayName: ZOO_AUTOPURGE_SANPRETAINCOUNT
  description: The number of snapshots to retain in dataDir
  required: true
  value: '3'
- name: ZOO_AUTOPURGE_PURGEINTERVAL
  displayName: ZOO_AUTOPURGE_PURGEINTERVAL
  description: Purge task interval in hours. Set to 0 to disable auto purge feature
  required: true
  value: '1'

objects:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: zookeeper
    annotations: {
        volume.alpha.kubernetes.io/storage-class: "fast"
    }
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: ${VOLUME_CAPACITY}

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: zookeeper
  spec:
    replicas: 1
    selector:
      deploymentconfig: zookeeper
    template:
      metadata:
        labels:
          deploymentconfig: zookeeper
      spec:
        containers:
        - name: server
          image: ${ZOOKEEPER_IMAGE}
          env:
          - name: ZOO_USER
            value: ${ZOO_USER}
          - name: ZOO_CONF_DIR
            value: ${ZOO_CONF_DIR}
          - name: ZOO_DATA_DIR
            value: ${ZOO_DATA_DIR}
          - name: ZOO_DATA_LOG_DIR
            value: ${ZOO_DATA_LOG_DIR}
          - name: ZOO_TICK_TIME
            value: ${ZOO_TICK_TIME}
          - name: ZOO_INIT_LIMIT
            value: ${ZOO_INIT_LIMIT}
          - name: ZOO_SYNC_LIMIT
            value: ${ZOO_SYNC_LIMIT}
          - name: ZOO_PORT
            value: ${ZOO_PORT}
          - name: ZOO_MAX_CLIENT_CNXNS
            value: ${ZOO_MAX_CLIENT_CNXNS}
          - name: ZOO_AUTOPURGE_SANPRETAINCOUNT
            value: ${ZOO_AUTOPURGE_SANPRETAINCOUNT}
          - name: ZOO_AUTOPURGE_PURGEINTERVAL
            value: ${ZOO_AUTOPURGE_PURGEINTERVAL}
          volumeMounts:
          - name: conf
            mountPath: ${ZOO_CONF_DIR}
          - name: data
            mountPath: ${ZOO_DATA_DIR}
          - name: log
            mountPath: ${ZOO_DATA_LOG_DIR}
          ports:
          - containerPort: ${ZOO_PORT}
            protocol: TCP
        volumes:
        - name: conf
          persistentVolumeClaim:
            claimName: zookeeper
        - name: data
          persistentVolumeClaim:
            claimName: zookeeper
        - name: log
          persistentVolumeClaim:
            claimName: zookeeper
    triggers:
    - type: ConfigChange
      configChangeParams:
        automatic: false

- apiVersion: v1
  kind: Service
  metadata:
    name: zookeeper
  spec:
    ports:
    - port: ${ZOO_PORT}
    selector:
      deploymentconfig: zookeeper