apiVersion: v1
kind: Template
metadata:
  name: ml-zk
  annotations:
    description: ZooKeeper
    tags: ML,messaging,zookeeper

parameters:
- name: VOLUME_CAPACITY
  description: Persistent volume capacity per pod, e.g. 512Mi, 2Gi
  required: true
  value: 512Mi
- name: NAME
  description: Name prefix for each object created
  required: true
  value: ml-zk
- name: IMAGESTREAM
  description: Image name
  required: true
  value: kafkanetes
- name: REPLICAS
  description: Number of replicas [1,3, ...]
  required: true
  value: 1

objects:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: ${NAME}
    annotations:
      volume.alpha.kubernetes.io/storage-class: ${NAME}
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: ${VOLUME_CAPACITY}

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: ${NAME}
  spec:
    replicas: ${REPLICAS}
    selector:
      deploymentconfig: ${NAME}
    template:
      metadata:
        labels:
          app: ${NAME}
          deploymentconfig: ${NAME}
      spec:
        containers:
        - name: ml-zk
          image: ${IMAGESTREAM}
          command:
          - bin/zookeeper-server-start-multiple.sh
          args:
          - config/zookeeper.properties
          - ${NAME}
          - "1"
          - "3"
          volumeMounts:
          - mountPath: /tmp/zookeeper
            name: zookeeper
          ports:
          - containerPort: 2181
          - containerPort: 2888
          - containerPort: 3888
        volumes:
        - name: zookeeper
          persistentVolumeClaim:
            claimName: ${NAME}
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: false
        containerNames:
        - ml-zk
        from:
          kind: ImageStream
          name: ${IMAGESTREAM}

- apiVersion: v1
  kind: Service
  metadata:
    name: ${NAME}
  spec:
    ports:
    - name: 2181-tcp
      port: 2181
    - name: 2888-tcp
      port: 2888
    - name: 3888-tcp
      port: 3888
    selector:
      deploymentconfig: ${NAME}
